#!/usr/bin/python3

import sys
import csv
from difflib import SequenceMatcher


usage = "\n This script compares the discovered passwords of two analysis \
runs and outputs the percentage similarity.  \n \
The script takes two arguments, which are the files to be compared.  \
The files should be in CSV format such as username,password as generated by \
the usermatch.py script \n \
\n \
\t pass-similarity.py passfile1.csv passfile2.csv \n \n"



if len(sys.argv) < 3:
    print(usage)
    exit()


# Create a dictionary from the CSV file    
def makedict(accounts):
    with open(accounts, newline='') as f:
        data = csv.reader(f, delimiter=',')
        mydict = {rows[0]:rows[1] for rows in data}
        return mydict


def comparepass(accts1, accts2):
    for account in accts1:
        if account in accts2:
            drift = round(SequenceMatcher(a=accts1[account],\
                    b=accts2[account]).ratio(),2)
            print(account + ',' + accts1[account] + ',' + accts2[account] \
                  + ',' + str(drift))
    
accts1 = makedict(sys.argv[1])
accts2 = makedict(sys.argv[2])

comparepass(accts1, accts2)
